import type { CvTemplateId } from "@matchfolio/shared";
import { ArrowRight, Check } from "lucide-react";
import { useState } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { PageHeader } from "../components/layout/PageHeader";
import { Badge } from "../components/ui/Badge";
import { Button } from "../components/ui/Button";
import { getCvById, updateCv } from "../db/cvRepository";
import { templateMetadata } from "../templates/templateMetadata";

export function TemplatesPage() { const [params] = useSearchParams(); const navigate = useNavigate(); const [error, setError] = useState(""); const select = async (templateId: CvTemplateId) => { const cvId = params.get("cvId"); if (!cvId) { navigate(`/cvs/new?template=${templateId}`); return; } try { const cv = await getCvById(cvId); if (!cv) throw new Error("CV not found."); await updateCv({ ...cv, templateId }); navigate(`/cvs/${cv.id}`); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not apply the template."); } }; return <><PageHeader title="Templates" description="Choose a professional layout without changing your structured CV content." />{error && <p role="alert" className="mb-4 text-sm text-red-600">{error}</p>}<div className="grid gap-5 md:grid-cols-2">{templateMetadata.map((template) => <article key={template.id} className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="h-48 bg-slate-100 p-6"><div className="mx-auto h-full max-w-52 bg-white p-4 shadow-sm"><div className={`h-2 w-24 ${template.id === "european-tech" ? "bg-teal-700" : "bg-slate-800"}`} /><div className="mt-3 h-1.5 w-36 bg-slate-300" /><div className="mt-6 space-y-2"><div className="h-1 bg-slate-200" /><div className="h-1 bg-slate-200" /><div className="h-1 w-4/5 bg-slate-200" /></div><div className="mt-5 h-1.5 w-20 bg-teal-700" /><div className="mt-2 space-y-2"><div className="h-1 bg-slate-200" /><div className="h-1 bg-slate-200" /></div></div></div><div className="p-6"><div className="flex items-start justify-between gap-3"><div><h2 className="text-lg font-bold text-slate-950">{template.name}</h2><p className="mt-1 text-xs font-semibold uppercase tracking-wide text-teal-700">{template.region}</p></div><Badge appearance="accent">Available</Badge></div><p className="mt-3 text-sm leading-6 text-slate-500">{template.description}</p><ul className="mt-4 grid gap-2 text-sm text-slate-600">{template.bestFor.map((item) => <li key={item} className="flex gap-2"><Check className="mt-0.5 size-4 shrink-0 text-teal-600" />{item}</li>)}</ul><Button className="mt-5 w-full" onClick={() => void select(template.id)}>Use template <ArrowRight className="size-4" /></Button></div></article>)}</div></>; }
