import type { Cv } from "@matchfolio/shared";
import { compact, dateRange } from "./templateUtils";

const Heading = ({ children }: { children: string }) => <h2 className="mb-2 mt-6 border-b-2 border-slate-800 pb-1 text-[12px] font-bold uppercase tracking-[0.1em] text-slate-900">{children}</h2>;
const Bullets = ({ items }: { items: string[] }) => <ul className="mt-1 list-disc space-y-1 pl-4">{items.filter(Boolean).map((item, index) => <li key={`${item}-${index}`}>{item}</li>)}</ul>;

export function AustralianProfessionalTemplate({ cv }: { cv: Cv }) { const p = cv.personalDetails; return <article className="min-h-[297mm] bg-white p-[16mm] font-sans text-[10px] leading-[1.55] text-slate-700"><header className="border-b-4 border-teal-700 pb-4"><h1 className="text-[27px] font-bold uppercase tracking-wide text-slate-950">{p.fullName || "Your Name"}</h1><p className="text-[13px] font-semibold text-slate-600">{p.professionalTitle}</p><p className="mt-2 text-[9.5px]">{compact([p.location, p.phone, p.email, p.linkedin])}</p></header>{cv.professionalSummary && <><Heading>Professional profile</Heading><p>{cv.professionalSummary}</p></>}{cv.skillGroups.length > 0 && <><Heading>Key skills</Heading><div className="grid grid-cols-2 gap-x-6">{cv.skillGroups.map((group) => <p key={group.id}><b>{group.name}:</b> {group.skills.join(", ")}</p>)}</div></>}{cv.workExperience.length > 0 && <><Heading>Career history</Heading><div className="space-y-4">{cv.workExperience.map((role) => <section key={role.id}><div className="flex justify-between gap-4"><h3 className="font-bold text-slate-950">{role.position} | {role.company}</h3><span>{dateRange(role.startDate, role.endDate, role.isCurrent)}</span></div>{role.location && <p className="text-slate-500">{role.location}</p>}{role.description && <><h4 className="mt-2 font-bold">Role overview</h4><p>{role.description}</p></>}{role.responsibilities.length > 0 && <><h4 className="mt-2 font-bold">Key responsibilities</h4><Bullets items={role.responsibilities} /></>}{role.achievements.length > 0 && <><h4 className="mt-2 font-bold">Key achievements</h4><Bullets items={role.achievements} /></>}</section>)}</div></>}<AustralianTail cv={cv} /></article>; }

function AustralianTail({ cv }: { cv: Cv }) { const available = cv.references.some((item) => item.isAvailableOnRequest); const named = cv.references.filter((item) => !item.isAvailableOnRequest); return <>{cv.education.length > 0 && <><Heading>Education</Heading>{cv.education.map((item) => <p key={item.id}><b>{item.degree}</b>, {item.institution} <span className="float-right">{dateRange(item.startDate, item.endDate, item.isCurrent)}</span></p>)}</>}{cv.certifications.length > 0 && <><Heading>Certifications</Heading>{cv.certifications.map((item) => <p key={item.id}>{compact([item.name, item.issuer, item.issueDate])}</p>)}</>}{cv.languages.length > 0 && <><Heading>Languages</Heading><p>{cv.languages.map((item) => compact([item.name, item.proficiency])).join(" · ")}</p></>}{cv.interests.length > 0 && <><Heading>Interests</Heading><p>{cv.interests.join(" · ")}</p></>}{(available || named.length > 0) && <><Heading>References</Heading>{available ? <p>References available upon request.</p> : named.map((item) => <p key={item.id}><b>{item.name}</b>{compact([item.position, item.company, item.email, item.phone]) ? ` — ${compact([item.position, item.company, item.email, item.phone])}` : ""}</p>)}</>}{cv.customSections.map((section) => <section key={section.id}><Heading>{section.title}</Heading>{section.items.map((item) => <div key={item.id}><b>{item.title}</b>{item.subtitle && ` — ${item.subtitle}`}<p>{item.description}</p><Bullets items={item.highlights} /></div>)}</section>)}</>; }
