import type { Cv } from "@matchfolio/shared";
import { compact, dateRange } from "./templateUtils";

const Heading = ({ children }: { children: string }) => <h2 className="mb-2 mt-5 border-b border-slate-300 pb-1 text-[11px] font-bold uppercase tracking-[0.16em] text-teal-800">{children}</h2>;
const Bullets = ({ items }: { items: string[] }) => items.length ? <ul className="mt-1 list-disc space-y-0.5 pl-4">{items.filter(Boolean).map((item, index) => <li key={`${item}-${index}`}>{item}</li>)}</ul> : null;

export function EuropeanTechTemplate({ cv }: { cv: Cv }) {
  const p = cv.personalDetails;
  return <article className="min-h-[297mm] bg-white p-[14mm] font-sans text-[9.5px] leading-[1.45] text-slate-700"><header><h1 className="text-[25px] font-bold tracking-tight text-slate-950">{p.fullName || "Your Name"}</h1><p className="mt-0.5 text-[12px] font-semibold text-teal-700">{p.professionalTitle}</p><p className="mt-2 text-[9px] text-slate-500">{compact([p.email, p.phone, p.location, p.website, p.linkedin, p.github])}</p></header>{cv.professionalSummary && <><Heading>Profile</Heading><p>{cv.professionalSummary}</p></>} {cv.workExperience.length > 0 && <><Heading>Work experience</Heading><div className="space-y-3">{cv.workExperience.map((role) => <section key={role.id}><div className="flex justify-between gap-4"><h3 className="font-bold text-slate-950">{role.position} – {role.company}</h3><span className="shrink-0 text-slate-500">{dateRange(role.startDate, role.endDate, role.isCurrent)}</span></div>{role.location && <p className="text-slate-500">{role.location}</p>}{role.description && <p className="mt-1">{role.description}</p>}<Bullets items={[...role.achievements, ...role.responsibilities]} />{role.technologies.length > 0 && <p className="mt-1"><b>Stack:</b> {role.technologies.join(", ")}</p>}</section>)}</div></>} {cv.projects.length > 0 && <><Heading>Projects</Heading><div className="space-y-2">{cv.projects.map((project) => <section key={project.id}><h3 className="font-bold text-slate-950">{project.name}{project.role ? ` — ${project.role}` : ""}</h3>{project.description && <p>{project.description}</p>}<Bullets items={project.highlights} />{project.technologies.length > 0 && <p><b>Technologies:</b> {project.technologies.join(", ")}</p>}</section>)}</div></>} {cv.skillGroups.length > 0 && <><Heading>Technical skills</Heading>{cv.skillGroups.map((group) => <p key={group.id}><b>{group.name}:</b> {group.skills.join(", ")}</p>)}</>}<CommonSections cv={cv} /></article>;
}

function CommonSections({ cv }: { cv: Cv }) { const references = cv.references.filter((item) => !item.isAvailableOnRequest); return <>{cv.education.length > 0 && <><Heading>Education</Heading>{cv.education.map((item) => <div key={item.id} className="mb-2"><div className="flex justify-between"><b className="text-slate-950">{item.degree}, {item.institution}</b><span>{dateRange(item.startDate, item.endDate, item.isCurrent)}</span></div><p>{compact([item.fieldOfStudy, item.location, item.grade])}</p><Bullets items={item.highlights} /></div>)}</>}{cv.certifications.length > 0 && <><Heading>Certifications</Heading>{cv.certifications.map((item) => <p key={item.id}><b>{item.name}</b>{compact([item.issuer, item.issueDate]) ? ` — ${compact([item.issuer, item.issueDate])}` : ""}</p>)}</>}{cv.languages.length > 0 && <><Heading>Languages</Heading><p>{cv.languages.map((item) => compact([item.name, item.proficiency])).join(" · ")}</p></>}{references.length > 0 && <><Heading>References</Heading>{references.map((item) => <p key={item.id}><b>{item.name}</b>{compact([item.position, item.company, item.email, item.phone]) ? ` — ${compact([item.position, item.company, item.email, item.phone])}` : ""}</p>)}</>}{cv.customSections.map((section) => <section key={section.id}><Heading>{section.title}</Heading>{section.items.map((item) => <div key={item.id} className="mb-2"><b>{item.title}</b>{item.subtitle && <span> — {item.subtitle}</span>}<p>{item.description}</p><Bullets items={item.highlights} /></div>)}</section>)}</>; }
